# -*- coding: utf-8 -*-
"""etl_vigiar_srag_2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e2IfN0-4g5CH7TNKgowsqrt3OlsSE9CN

# ETL VigiAr — SRAG 2024 → mesma estrutura da base de 2025

Este notebook reaproveita **as mesmas funções, nomes de coluna e regras de cálculo** do
`etl_vigiar_colab_v3.py` (o script que vocês já usaram para gerar a base de 2025), adaptando
apenas os trechos que dependem do **formato do arquivo bruto**, que é diferente em 2024.
Duas colunas novas em relação a 2025: `idade_media` e `CO_REGIONA`.

## Antes de rodar

**Nomes de arquivo.** Configure os caminhos exatos na célula de configuração logo abaixo.
Os nomes padrão já correspondem aos arquivos que você me enviou — mas quando você
subir os mesmos arquivos aqui no Colab, dê uma conferida se o nome bate exatamente
(o Claude às vezes adiciona um sufixo tipo `__1_` ou `(1)` quando um arquivo é reenviado no chat;
isso não deve acontecer no seu upload direto pro Colab, mas vale checar com `!ls`).

**Tempo de execução.** A célula de geocodificação (região + proximidade de temperatura) usa o
Nominatim/OpenStreetMap, que limita a 1 requisição por segundo. Para ~645 municípios + ~15
estações, espere **10 a 15 minutos** nessa célula — é a mesma técnica já usada na base de 2025,
mantida aqui de propósito para preservar a mesma regra de cálculo de `regiao` e `temp_imputada`.

## Pontos em aberto (peço para você confirmar antes de consolidar com 2025)

1. **`leitos_uti_adulto_sus`, `leitos_uti_pediatrico_sus`, `leitos_uti_neonatal_sus` saem
   zeradas.** O arquivo de 2025 (`Leitos_2025.csv`) já vinha pré-agregado por especialidade de UTI
   (extrato do TABNET/CNES). O arquivo de 2024 (`cnes_consolidado_2024.csv`) é o extrato BRUTO do
   CNES, com o tipo de leito em código numérico (`CODLEITO`), e a tabela oficial de códigos foi
   reformulada em 2023/2024 (Portaria SAES/MS 3.511/2025) — não consegui confirmar com segurança
   qual código corresponde a cada especialidade nessa nova numeração. **Sugestão:** se for possível
   gerar um `Leitos_2024.csv` no mesmo formato do `Leitos_2025.csv` (mesmo relatório do TABNET), o
   pipeline fica 100% equivalente — só trocar a função de carga. `LEITOS_EXISTENTES`, `LEITOS_SUS`,
   `leitos_uti_sus` (total) e `n_hospitais_sus` **estão corretos** desde já, pois não dependem
   dessa quebra fina.
2. **Semanas de fronteira entre anos.** Assim como a própria base de 2025 já tem algumas linhas
   com `ano=2024`/`ano=2026` na ponta (efeito colateral do notebook original: `ano` vem do ano civil
   do início da semana, e `semana_numero` vem do calendário ISO — os dois podem divergir na virada
   do ano), a base de 2024 vai sair com algumas linhas `ano=2023` e `ano=2025` pelo mesmo motivo
   (o arquivo bruto de notificação tem registros um pouco antes/depois do ano-calendário). Isso é
   esperado e consistente com o que já existe na base de 2025 — mas ao consolidar as duas bases,
   você vai ter *algumas* semanas se sobrepondo (ex: a mesma semana pode aparecer no fim do arquivo
   de 2024 e no início do arquivo de 2025). Recomendo, na hora de consolidar, decidir uma regra de
   desempate (ex: manter a linha vinda do arquivo do ano em que a maior parte da semana cai).
3. **`idade_media`** segue a mesma regra já usada para `casos_idosos` na base de 2025: só conta
   quando a idade veio informada em **anos** no SIVEP-Gripe (campo `TP_IDADE`). Registros de bebês
   com idade em dias/meses ficam de fora da média (não convertidos para fração de ano), por
   consistência com a lógica já validada — mas isso significa que a idade média de municípios com
   muitos casos pediátricos pode ficar levemente superestimada.
"""

# ============================================================
# CONFIGURAÇÃO — ajuste os nomes de arquivo se necessário
# ============================================================
import os

PASTA_DADOS = "/content"   # ajuste se estiver usando Google Drive

SRAG_2024_PATH = os.path.join(PASTA_DADOS, "Srag_2024.csv")
TEMPERATURA_2024_PATH = os.path.join(PASTA_DADOS, "temperatura_sp_2024.csv")
POPULACAO_2024_PATH = os.path.join(PASTA_DADOS, "populacao_sp_2024_oficial.csv")
CNES_2024_PATH = os.path.join(PASTA_DADOS, "cnes_consolidado_2024.csv")
VIGIAR_REF_PATH = os.path.join(PASTA_DADOS, "vigiar_sp_formatado.xlsx")  # para validação e para a região de 2025

SAIDA = os.path.join(PASTA_DADOS, "dataset_vigiar_sp_2024.csv")
SAIDA_SQL = os.path.join(PASTA_DADOS, "comentarios_tabela_vigiar.sql")

UF_ALVO = "SP"

for nome, caminho in [("SRAG", SRAG_2024_PATH), ("Temperatura", TEMPERATURA_2024_PATH),
                       ("População", POPULACAO_2024_PATH), ("CNES", CNES_2024_PATH),
                       ("Referência 2025", VIGIAR_REF_PATH)]:
    print(f"{'OK' if os.path.exists(caminho) else 'NÃO ENCONTRADO'} — {nome}: {caminho}")

!pip install geopy --quiet

import os
import json
import time
import unicodedata
import re
from math import radians, sin, cos, sqrt, atan2

import numpy as np
import pandas as pd

"""## Funções reaproveitadas do ETL de 2025 (sem mudança de lógica)"""

# ========================================================================
# BLOCO REAPROVEITADO DO ETL ORIGINAL (2025) — SEM MUDANÇA DE LÓGICA
# ========================================================================

EXCECOES_NOME_MUNICIPIO = {
    "MOJI MIRIM": "MOGI MIRIM",
    "SAO LUIS DO PARAITINGA": "SAO LUIZ DO PARAITINGA",
    "BIRITIBA MIRIM": "BIRITIBA-MIRIM",
}


def normalizar_municipio(texto):
    texto = str(texto).upper().strip()
    texto = unicodedata.normalize("NFKD", texto).encode("ASCII", "ignore").decode("ASCII")
    texto = EXCECOES_NOME_MUNICIPIO.get(texto, texto)
    return texto


def formatar_data_br(data):
    if pd.isna(data):
        return "Não informado"
    return pd.Timestamp(data).strftime("%d/%m/%Y")


def ler_csv_seguro(caminho, **kwargs):
    for encoding in ("utf-8", "latin1"):
        try:
            df = pd.read_csv(caminho, encoding=encoding, **kwargs)
            if df.shape[1] <= 1:
                raise pd.errors.ParserError("Apenas 1 coluna detectada")
            return df
        except UnicodeDecodeError:
            continue
        except pd.errors.ParserError:
            print(f"Aviso: {os.path.basename(caminho)} não usa ',' como separador — detectando automaticamente...")
            return pd.read_csv(caminho, encoding=encoding, sep=None, engine="python", on_bad_lines="skip", **kwargs)
    raise UnicodeDecodeError(f"Não foi possível ler {caminho} nem com utf-8 nem com latin1.")


MAPA_SIM_NAO = {1: "Sim", 2: "Não", 9: "Ignorado"}
MAPA_UTI = {1: "Sim", 2: "Não", 9: "Ignorado"}
MAPA_VACINA = {1: "Sim", 2: "Não", 9: "Ignorado"}
MAPA_TP_IDADE = {1: "Dia", 2: "Mês", 3: "Ano"}
MAPA_EVOLUCAO = {1: "Cura", 2: "Óbito", 3: "Óbito por outras causas", 9: "Ignorado"}
MAPA_CLASSI_FIN = {
    1: "SRAG por influenza",
    2: "SRAG por outro vírus respiratório",
    3: "SRAG por outro agente etiológico",
    4: "SRAG não especificado",
    5: "SRAG por covid-19",
}
MAPA_SUPORT_VEN = {1: "Sim, invasivo", 2: "Sim, não invasivo", 3: "Não", 9: "Ignorado"}
MAPA_PCR_RESUL = {1: "Detectável", 2: "Não detectável", 3: "Inconclusivo",
                   4: "Não realizado", 5: "Aguardando resultado", 9: "Ignorado"}
MAPA_RES_AN = {1: "Positivo", 2: "Negativo", 3: "Inconclusivo",
               4: "Não realizado", 5: "Aguardando resultado", 9: "Ignorado"}
MAPA_CS_GESTANT = {1: "1º trimestre", 2: "2º trimestre", 3: "3º trimestre",
                    4: "Idade gestacional ignorada", 5: "Não", 6: "Não se aplica", 9: "Ignorado"}
MAPA_CS_ZONA = {1: "Urbana", 2: "Rural", 3: "Periurbana", 9: "Ignorado"}


def decodificar_categoria(serie, mapa):
    numerico = pd.to_numeric(serie, errors="coerce")
    return numerico.map(mapa).fillna("Não informado")


def serie_segura(df, coluna):
    if coluna not in df.columns:
        print(f"Aviso: coluna '{coluna}' não encontrada — variáveis derivadas dela ficarão vazias.")
        return pd.Series([None] * len(df), index=df.index)
    return df[coluna]

"""## Etapa 1 — SRAG 2024 (mesmas regras; + `idade_media` e `CO_REGIONA`)"""

# ========================================================================
# ETAPA 1 — SRAG 2024 (idêntico ao ETL de 2025, só muda o arquivo de entrada)
# + as 2 colunas novas: idade_media e CO_REGIONA
# ========================================================================

def carregar_srag_2024():
    print("Carregando SRAG 2024...")
    df = ler_csv_seguro(SRAG_2024_PATH, sep=";", dtype=str)

    coluna_uf = "SG_UF_NOT"
    coluna_data = "DT_NOTIFIC"
    coluna_municipio_resi = "ID_MN_RESI"
    coluna_regional = "ID_REGIONA"
    coluna_co_regional = "CO_REGIONA"  # NOVO: código numérico oficial da regional

    df = df[df[coluna_uf] == UF_ALVO].copy()

    df["data_notificacao"] = pd.to_datetime(df[coluna_data], errors="coerce")
    df["semana"] = df["data_notificacao"].dt.to_period("W")

    df["municipio"] = df[coluna_municipio_resi].apply(normalizar_municipio)

    df["regional_saude"] = df[coluna_regional].fillna("Não informado") if coluna_regional in df.columns else "Não informado"
    # NOVO: CO_REGIONA — código numérico da regional (complementa regional_saude,
    # que é o nome em texto). Mesma regra: "primeiro valor não nulo do grupo".
    df["co_regiona_num"] = pd.to_numeric(serie_segura(df, coluna_co_regional), errors="coerce")

    df["classi_fin_decodificado"] = decodificar_categoria(df["CLASSI_FIN"], MAPA_CLASSI_FIN)
    df["evolucao_decodificada"] = decodificar_categoria(df["EVOLUCAO"], MAPA_EVOLUCAO)
    df["uti_decodificado"] = decodificar_categoria(df["UTI"], MAPA_UTI)
    df["vacina_decodificado"] = decodificar_categoria(df["VACINA"], MAPA_VACINA)
    df["tp_idade_decodificado"] = decodificar_categoria(df["TP_IDADE"], MAPA_TP_IDADE)

    colunas_comorbidade = [
        "CARDIOPATI", "DIABETES", "ASMA", "OBESIDADE",
        "IMUNODEPRE", "RENAL", "PNEUMOPATI", "NEUROLOGIC",
    ]
    for coluna in colunas_comorbidade:
        df[f"{coluna.lower()}_decodificado"] = decodificar_categoria(df[coluna], MAPA_SIM_NAO)

    df["surto_decodificado"] = decodificar_categoria(serie_segura(df, "SURTO_SG"), MAPA_SIM_NAO)
    df["saturacao_decodificada"] = decodificar_categoria(serie_segura(df, "SATURACAO"), MAPA_SIM_NAO)
    df["dispneia_decodificada"] = decodificar_categoria(serie_segura(df, "DISPNEIA"), MAPA_SIM_NAO)
    df["desc_resp_decodificado"] = decodificar_categoria(serie_segura(df, "DESC_RESP"), MAPA_SIM_NAO)
    df["suport_ven_decodificado"] = decodificar_categoria(serie_segura(df, "SUPORT_VEN"), MAPA_SUPORT_VEN)
    df["pcr_resul_decodificado"] = decodificar_categoria(serie_segura(df, "PCR_RESUL"), MAPA_PCR_RESUL)
    df["res_an_decodificado"] = decodificar_categoria(serie_segura(df, "RES_AN"), MAPA_RES_AN)
    df["amostra_decodificada"] = decodificar_categoria(serie_segura(df, "AMOSTRA"), MAPA_SIM_NAO)
    df["fator_risc_decodificado"] = decodificar_categoria(serie_segura(df, "FATOR_RISC"), MAPA_SIM_NAO)
    df["cs_gestant_decodificado"] = decodificar_categoria(serie_segura(df, "CS_GESTANT"), MAPA_CS_GESTANT)
    df["tabag_decodificado"] = decodificar_categoria(serie_segura(df, "TABAG"), MAPA_SIM_NAO)
    df["cs_zona_decodificada"] = decodificar_categoria(serie_segura(df, "CS_ZONA"), MAPA_CS_ZONA)
    df["vacina_cov_decodificada"] = decodificar_categoria(serie_segura(df, "VACINA_COV"), MAPA_SIM_NAO)
    df["febre_decodificada"] = decodificar_categoria(serie_segura(df, "FEBRE"), MAPA_SIM_NAO)
    df["tosse_decodificada"] = decodificar_categoria(serie_segura(df, "TOSSE"), MAPA_SIM_NAO)
    df["an_sars2_decodificado"] = decodificar_categoria(serie_segura(df, "AN_SARS2"), MAPA_SIM_NAO)
    df["pcr_sars2_decodificado"] = decodificar_categoria(serie_segura(df, "PCR_SARS2"), MAPA_SIM_NAO)
    df["an_vsr_decodificado"] = decodificar_categoria(serie_segura(df, "AN_VSR"), MAPA_SIM_NAO)
    df["pcr_vsr_decodificado"] = decodificar_categoria(serie_segura(df, "PCR_VSR"), MAPA_SIM_NAO)

    df["eh_influenza"] = df["classi_fin_decodificado"] == "SRAG por influenza"
    df["eh_covid"] = df["classi_fin_decodificado"] == "SRAG por covid-19"
    df["eh_obito"] = df["evolucao_decodificada"].isin(["Óbito", "Óbito por outras causas"])
    df["foi_uti"] = df["uti_decodificado"] == "Sim"
    df["foi_vacinado"] = df["vacina_decodificado"] == "Sim"

    tem_comorbidade = pd.Series(False, index=df.index)
    for coluna in colunas_comorbidade:
        tem_comorbidade = tem_comorbidade | (df[f"{coluna.lower()}_decodificado"] == "Sim")
    df["tem_comorbidade"] = tem_comorbidade

    # idade em anos só é confiável quando TP_IDADE decodificado == "Ano"
    # (mesma regra usada em 2025 para eh_idoso; idade_media segue o mesmo
    # critério, por consistência)
    idade_em_anos = pd.to_numeric(df["NU_IDADE_N"], errors="coerce").where(
        df["tp_idade_decodificado"] == "Ano"
    )
    df["idade_anos"] = idade_em_anos
    df["eh_idoso"] = idade_em_anos >= 60

    df["eh_surto"] = df["surto_decodificado"] == "Sim"
    df["eh_saturacao_baixa"] = df["saturacao_decodificada"] == "Sim"
    df["eh_dispneia"] = df["dispneia_decodificada"] == "Sim"
    df["eh_desc_resp"] = df["desc_resp_decodificado"] == "Sim"
    df["eh_vent_invasiva"] = df["suport_ven_decodificado"] == "Sim, invasivo"
    df["eh_pcr_positivo"] = df["pcr_resul_decodificado"] == "Detectável"
    df["eh_antigenico_positivo"] = df["res_an_decodificado"] == "Positivo"
    df["eh_sars2"] = (df["an_sars2_decodificado"] == "Sim") | (df["pcr_sars2_decodificado"] == "Sim")
    df["eh_vsr"] = (df["an_vsr_decodificado"] == "Sim") | (df["pcr_vsr_decodificado"] == "Sim")
    df["foi_testado"] = df["amostra_decodificada"] == "Sim"
    df["tem_fator_risco"] = df["fator_risc_decodificado"] == "Sim"
    df["eh_gestante"] = df["cs_gestant_decodificado"].isin(
        ["1º trimestre", "2º trimestre", "3º trimestre", "Idade gestacional ignorada"]
    )
    df["eh_tabagista"] = df["tabag_decodificado"] == "Sim"
    df["eh_zona_rural"] = df["cs_zona_decodificada"] == "Rural"
    df["foi_vacinado_covid"] = df["vacina_cov_decodificada"] == "Sim"
    df["teve_febre"] = df["febre_decodificada"] == "Sim"
    df["teve_tosse"] = df["tosse_decodificada"] == "Sim"

    df["municipio_internacao"] = serie_segura(df, "ID_MN_INTE").apply(
        lambda v: normalizar_municipio(v) if pd.notna(v) else v
    )
    df["foi_referenciado"] = (
        df["municipio_internacao"].notna()
        & (df["municipio_internacao"] != df["municipio"])
    )

    df["dt_sin_pri"] = pd.to_datetime(serie_segura(df, "DT_SIN_PRI"), errors="coerce")
    df["dt_coleta"] = pd.to_datetime(serie_segura(df, "DT_COLETA"), errors="coerce")
    df["dt_interna"] = pd.to_datetime(serie_segura(df, "DT_INTERNA"), errors="coerce")
    df["dt_digita"] = pd.to_datetime(serie_segura(df, "DT_DIGITA"), errors="coerce")
    df["dt_evoluca"] = pd.to_datetime(serie_segura(df, "DT_EVOLUCA"), errors="coerce")
    df["dt_entuti"] = pd.to_datetime(serie_segura(df, "DT_ENTUTI"), errors="coerce")
    df["dt_saiduti"] = pd.to_datetime(serie_segura(df, "DT_SAIDUTI"), errors="coerce")

    df["dias_ate_notificacao"] = (df["data_notificacao"] - df["dt_sin_pri"]).dt.days
    df["dias_ate_coleta"] = (df["dt_coleta"] - df["dt_sin_pri"]).dt.days
    df["dias_ate_internacao"] = (df["dt_interna"] - df["dt_sin_pri"]).dt.days
    df["dias_uti"] = (df["dt_saiduti"] - df["dt_entuti"]).dt.days
    df["dias_ate_digitacao"] = (df["dt_digita"] - df["data_notificacao"]).dt.days
    df["dias_ate_desfecho"] = (df["dt_evoluca"] - df["dt_interna"]).dt.days

    def moda_ou_primeiro(s):
        s = s.dropna()
        return s.iloc[0] if len(s) else np.nan

    agregados = df.groupby(["municipio", "semana"]).agg(
        regional_saude=("regional_saude", "first"),
        CO_REGIONA=("co_regiona_num", moda_ou_primeiro),      # NOVO
        idade_media=("idade_anos", "mean"),                    # NOVO
        casos_srag=("municipio", "size"),
        casos_influenza=("eh_influenza", "sum"),
        casos_covid=("eh_covid", "sum"),
        obitos=("eh_obito", "sum"),
        casos_uti=("foi_uti", "sum"),
        casos_com_comorbidade=("tem_comorbidade", "sum"),
        casos_vacinados=("foi_vacinado", "sum"),
        casos_idosos=("eh_idoso", "sum"),
        casos_surto=("eh_surto", "sum"),
        casos_saturacao_baixa=("eh_saturacao_baixa", "sum"),
        casos_dispneia=("eh_dispneia", "sum"),
        casos_desc_resp=("eh_desc_resp", "sum"),
        casos_vent_invasiva=("eh_vent_invasiva", "sum"),
        tempo_medio_uti_dias=("dias_uti", "mean"),
        casos_pcr_positivo=("eh_pcr_positivo", "sum"),
        casos_antigenico_positivo=("eh_antigenico_positivo", "sum"),
        casos_sars2=("eh_sars2", "sum"),
        casos_vsr=("eh_vsr", "sum"),
        casos_testados=("foi_testado", "sum"),
        atraso_notificacao_dias=("dias_ate_notificacao", "mean"),
        atraso_coleta_dias=("dias_ate_coleta", "mean"),
        atraso_internacao_dias=("dias_ate_internacao", "mean"),
        casos_fator_risco=("tem_fator_risco", "sum"),
        casos_gestantes=("eh_gestante", "sum"),
        casos_tabagistas=("eh_tabagista", "sum"),
        casos_zona_rural=("eh_zona_rural", "sum"),
        casos_vacinados_covid=("foi_vacinado_covid", "sum"),
        casos_febre=("teve_febre", "sum"),
        casos_tosse=("teve_tosse", "sum"),
        atraso_digitacao_dias=("dias_ate_digitacao", "mean"),
        tempo_ate_desfecho_dias=("dias_ate_desfecho", "mean"),
        casos_referenciados=("foi_referenciado", "sum"),
    ).reset_index()

    agregados["taxa_obito"] = agregados["obitos"] / agregados["casos_srag"]
    agregados["taxa_uti"] = agregados["casos_uti"] / agregados["casos_srag"]
    agregados["taxa_comorbidade"] = agregados["casos_com_comorbidade"] / agregados["casos_srag"]
    agregados["taxa_vacinados"] = agregados["casos_vacinados"] / agregados["casos_srag"]
    agregados["taxa_idosos"] = agregados["casos_idosos"] / agregados["casos_srag"]

    agregados["taxa_cadeia_surto"] = agregados["casos_surto"] / agregados["casos_srag"]
    agregados["taxa_saturacao_baixa"] = agregados["casos_saturacao_baixa"] / agregados["casos_srag"]
    agregados["taxa_dispneia"] = agregados["casos_dispneia"] / agregados["casos_srag"]
    agregados["taxa_desc_respiratorio"] = agregados["casos_desc_resp"] / agregados["casos_srag"]
    agregados["taxa_ventilacao_invasiva"] = agregados["casos_vent_invasiva"] / agregados["casos_srag"]
    agregados["taxa_positividade_pcr"] = (
        agregados["casos_pcr_positivo"] / agregados["casos_testados"].replace(0, pd.NA)
    )
    agregados["taxa_positividade_antigenico"] = (
        agregados["casos_antigenico_positivo"] / agregados["casos_testados"].replace(0, pd.NA)
    )
    agregados["taxa_sars2"] = agregados["casos_sars2"] / agregados["casos_srag"]
    agregados["taxa_vsr"] = agregados["casos_vsr"] / agregados["casos_srag"]
    agregados["taxa_testagem"] = agregados["casos_testados"] / agregados["casos_srag"]
    agregados["taxa_fator_risco"] = agregados["casos_fator_risco"] / agregados["casos_srag"]
    agregados["taxa_gestantes"] = agregados["casos_gestantes"] / agregados["casos_srag"]
    agregados["taxa_tabagismo"] = agregados["casos_tabagistas"] / agregados["casos_srag"]
    agregados["taxa_zona_rural"] = agregados["casos_zona_rural"] / agregados["casos_srag"]
    agregados["taxa_vacinacao_covid"] = agregados["casos_vacinados_covid"] / agregados["casos_srag"]
    agregados["taxa_febre"] = agregados["casos_febre"] / agregados["casos_srag"]
    agregados["taxa_tosse"] = agregados["casos_tosse"] / agregados["casos_srag"]
    agregados["indice_fluxo_referencia_hospitalar"] = agregados["casos_referenciados"] / agregados["casos_srag"]

    print("SRAG 2024: OK —", len(agregados), "combinações município x semana com pelo menos 1 caso")
    return agregados

"""## Etapas 2 a 4 — Leitos, População e Temperatura (adaptados ao formato de 2024)"""

_COD_PARA_NOME_MUNICIPIO = None  # preenchido por carregar_populacao_2024()

# ========================================================================
# ETAPA 2 — LEITOS 2024 (ADAPTADO — formato diferente do Leitos_2025.csv)
# ========================================================================
# O pipeline de 2025 usava um extrato já pré-agregado do CNES/TABNET
# (Leitos_2025.csv), com colunas prontas UTI_ADULTO_SUS / UTI_PEDIATRICO_SUS /
# UTI_NEONATAL_SUS. O arquivo de 2024 (cnes_consolidado_2024.csv) é o extrato
# BRUTO do CNES (uma linha por tipo de leito/estabelecimento/mês, com código
# numérico CODLEITO em vez do nome da especialidade).
#
# LEITOS_EXISTENTES, LEITOS_SUS, leitos_uti_sus (total) e n_hospitais_sus são
# calculados com segurança a partir do arquivo bruto (TP_LEITO == '7' = UTI).
# A quebra fina (adulto/pediátrico/neonatal) exigiria a tabela oficial de
# códigos CODLEITO pós-reforma 2023/2024, que não veio junto — por isso essas
# 3 colunas saem zeradas aqui. RECOMENDAÇÃO: se possível, gerar um
# "Leitos_2024.csv" no MESMO formato do Leitos_2025.csv (mesmo relatório do
# TABNET/CNES que vocês já usaram) — aí basta trocar de função de carga sem
# mexer no resto do pipeline.

def carregar_leitos_2024():
    print("Carregando Leitos (CNES bruto) 2024...")
    cnes = ler_csv_seguro(CNES_2024_PATH, sep=";", dtype=str)
    cnes.columns = [c.replace("\ufeff", "").replace("ï»¿", "").strip() for c in cnes.columns]

    ultima_competencia = cnes["COMPETEN"].max()
    print(f"  Competência usada como referência (snapshot mais recente): {ultima_competencia}")
    cnes = cnes[cnes["COMPETEN"] == ultima_competencia].copy()

    for c in ["QT_EXIST", "QT_SUS"]:
        cnes[c] = pd.to_numeric(cnes[c], errors="coerce").fillna(0)

    # tabela de correspondência código de município (6 dígitos) -> nome,
    # construída a partir do próprio SRAG 2024 (evita divergência de acentuação)
    global _COD_PARA_NOME_MUNICIPIO
    cnes["municipio"] = cnes["CODUFMUN"].astype(str).map(_COD_PARA_NOME_MUNICIPIO)
    cnes = cnes[cnes["municipio"].notna()]

    leitos_existentes = cnes.groupby("municipio")["QT_EXIST"].sum()
    leitos_sus = cnes.groupby("municipio")["QT_SUS"].sum()
    leitos_uti_sus = cnes[cnes["TP_LEITO"] == "7"].groupby("municipio")["QT_SUS"].sum()
    n_hospitais_sus = (
        cnes[cnes["QT_SUS"] > 0].groupby("municipio")["CNES"].nunique()
    )

    ocupacao = pd.DataFrame({
        "LEITOS_EXISTENTES": leitos_existentes,
        "LEITOS_SUS": leitos_sus,
        "leitos_uti_sus": leitos_uti_sus,
        "n_hospitais_sus": n_hospitais_sus,
    }).fillna(0).reset_index()

    # placeholders — ver nota acima
    ocupacao["leitos_uti_adulto_sus"] = 0
    ocupacao["leitos_uti_pediatrico_sus"] = 0
    ocupacao["leitos_uti_neonatal_sus"] = 0

    ocupacao["proporcao_leitos_sus"] = ocupacao["LEITOS_SUS"] / ocupacao["LEITOS_EXISTENTES"]

    print("Leitos 2024: OK (leitos_uti_adulto/pediatrico/neonatal_sus pendentes — ver nota no código)")
    return ocupacao


# ========================================================================
# ETAPA 3 — POPULAÇÃO 2024 (ADAPTADO — CSV oficial em vez do JSON do IBGE)
# ========================================================================

def carregar_populacao_2024():
    print("Carregando População 2024...")
    pop = ler_csv_seguro(POPULACAO_2024_PATH, sep=";", dtype=str)
    pop["municipio"] = pop["municipio"].apply(normalizar_municipio)
    pop["populacao"] = pd.to_numeric(pop["populacao_2024"], errors="coerce")

    # guarda o mapa codigo_datasus (6 digitos) -> nome normalizado, reusado
    # pela carga de leitos (cnes usa o mesmo codigo de município)
    global _COD_PARA_NOME_MUNICIPIO
    _COD_PARA_NOME_MUNICIPIO = pop.set_index(pop["cod_datasus_6d"].astype(str))["municipio"]

    print("População 2024: OK —", len(pop), "municípios")
    return pop[["municipio", "populacao"]]


# ========================================================================
# ETAPA 4 — TEMPERATURA 2024 (ADAPTADO — 1 arquivo consolidado em vez de 1
# arquivo por estação; mesma lógica de agregação semanal e mesma função de
# imputação por proximidade geográfica do ETL original)
# ========================================================================

def carregar_temperatura_sp_2024():
    print("Carregando Temperatura 2024...")
    temp = ler_csv_seguro(TEMPERATURA_2024_PATH, encoding_errors="ignore")
    temp.columns = [c.strip() for c in temp.columns]

    col_temp = [c for c in temp.columns if "BULBO SECO" in c.upper()][0]
    temp["temp_media_hora"] = pd.to_numeric(
        temp[col_temp].astype(str).str.replace(",", "."), errors="coerce"
    )
    temp["data"] = pd.to_datetime(temp["Data"], errors="coerce")
    temp["semana"] = temp["data"].dt.to_period("W")

    # extrai a cidade da estação a partir de "municipio_origem", ex.:
    # INMET_SE_SP_A716_OURINHOS_01-01-2024_A_31-12-2024 -> OURINHOS
    def extrai_cidade(nome):
        m = re.match(r"INMET_\w+_\w+_\w+_(.+?)_\d{2}-\d{2}-\d{4}", str(nome))
        return normalizar_municipio(m.group(1).replace("_", " ")) if m else None

    temp["cidade_estacao"] = temp["municipio_origem"].apply(extrai_cidade)

    resumo_semanal = (
        temp.dropna(subset=["cidade_estacao"])
        .groupby(["cidade_estacao", "semana"])["temp_media_hora"]
        .mean()
        .reset_index()
        .rename(columns={"temp_media_hora": "temp_media", "cidade_estacao": "municipio"})
    )

    print("Temperatura 2024: OK —", resumo_semanal["municipio"].nunique(), "estações")
    return resumo_semanal

"""## Geocodificação, região e imputação de temperatura (idêntico a 2025)"""

# ========================================================================
# GEOCODIFICAÇÃO + REGIÃO + IMPUTAÇÃO DE TEMPERATURA (idêntico ao ETL de 2025)
# ========================================================================
# ATENÇÃO: geocodifica 1 município/estação por segundo (limite do Nominatim/
# OpenStreetMap, gratuito). Para ~645 municípios + ~40 estações, espere
# 10-15 minutos nesta célula. É a MESMA técnica usada na base de 2025 —
# manter aqui garante que "regiao" seja calculada com a mesma regra.

def geocodificar_municipios(lista_municipios, pausa_segundos=1.0):
    from geopy.geocoders import Nominatim
    geolocator = Nominatim(user_agent="vigiar_etl_fiap_2024")
    coordenadas = {}
    for i, municipio in enumerate(lista_municipios, start=1):
        try:
            local = geolocator.geocode(f"{municipio}, São Paulo, Brasil", timeout=10)
            coordenadas[municipio] = {"lat": local.latitude, "lon": local.longitude} if local else {"lat": None, "lon": None}
        except Exception:
            coordenadas[municipio] = {"lat": None, "lon": None}
        time.sleep(pausa_segundos)
        if i % 50 == 0:
            print(f"  {i}/{len(lista_municipios)} geocodificados")
    return coordenadas


def classificar_regiao(municipios_coords):
    lats = [c["lat"] for c in municipios_coords.values() if c["lat"] is not None]
    lons = [c["lon"] for c in municipios_coords.values() if c["lon"] is not None]
    if not lats or not lons:
        return {m: "Não informado" for m in municipios_coords}

    lat_central, lon_central = np.median(lats), np.median(lons)
    margem_lat = (max(lats) - min(lats)) / 6 or 0.01
    margem_lon = (max(lons) - min(lons)) / 6 or 0.01

    regioes = {}
    for municipio, coord in municipios_coords.items():
        if coord["lat"] is None or coord["lon"] is None:
            regioes[municipio] = "Não informado"
            continue
        delta_lat = coord["lat"] - lat_central
        delta_lon = coord["lon"] - lon_central
        if abs(delta_lat) < margem_lat and abs(delta_lon) < margem_lon:
            regioes[municipio] = "Centro"
        elif abs(delta_lat) / margem_lat >= abs(delta_lon) / margem_lon:
            regioes[municipio] = "Norte" if delta_lat > 0 else "Sul"
        else:
            regioes[municipio] = "Leste" if delta_lon > 0 else "Oeste"
    return regioes


def preencher_temperatura_por_proximidade(dataset, temperatura, estacoes_coords, municipios_coords):
    dataset = dataset.copy()
    dataset["temp_imputada"] = dataset["temp_media"].isna()

    def estacao_mais_proxima(lat, lon):
        melhor, menor_dist = None, float("inf")
        for nome_estacao, info in estacoes_coords.items():
            if info["lat"] is None or info["lon"] is None:
                continue
            R = 6371
            dlat, dlon = radians(info["lat"] - lat), radians(info["lon"] - lon)
            a = sin(dlat / 2) ** 2 + cos(radians(lat)) * cos(radians(info["lat"])) * sin(dlon / 2) ** 2
            dist = R * 2 * atan2(sqrt(a), sqrt(1 - a))
            if dist < menor_dist:
                menor_dist, melhor = dist, nome_estacao
        return melhor

    mapa_estacao_mais_proxima = {}
    for municipio in dataset.loc[dataset["temp_imputada"], "municipio"].unique():
        coord = municipios_coords.get(municipio, {"lat": None, "lon": None})
        if coord["lat"] is None:
            mapa_estacao_mais_proxima[municipio] = None
        else:
            mapa_estacao_mais_proxima[municipio] = estacao_mais_proxima(coord["lat"], coord["lon"])

    def buscar_temp_proxima(linha):
        if not linha["temp_imputada"]:
            return linha["temp_media"]
        estacao_proxima = mapa_estacao_mais_proxima.get(linha["municipio"])
        if estacao_proxima is None:
            return None
        valores = temperatura.loc[
            (temperatura["municipio"] == estacao_proxima) & (temperatura["semana"] == linha["semana"]),
            "temp_media"
        ]
        return valores.iloc[0] if len(valores) else None

    dataset["temp_media"] = dataset.apply(buscar_temp_proxima, axis=1)
    n_imputadas = dataset.loc[dataset["temp_imputada"], "temp_media"].notna().sum()
    print(f"{n_imputadas} de {dataset['temp_imputada'].sum()} linhas preenchidas por proximidade.")
    return dataset

"""## Grade completa município × semana + união (idêntico a 2025)"""

# ========================================================================
# GRADE COMPLETA + UNIÃO (idêntico ao ETL de 2025)
# ========================================================================

def completar_grade_e_unir(srag, populacao, leitos, temperatura):
    municipios_sp = set(populacao["municipio"])
    n_municipios_antes = srag["municipio"].nunique()
    n_linhas_antes = len(srag)
    srag = srag[srag["municipio"].isin(municipios_sp)].copy()
    n_municipios_removidos = n_municipios_antes - srag["municipio"].nunique()
    n_linhas_removidas = n_linhas_antes - len(srag)
    if n_municipios_removidos > 0:
        print(f"SRAG: removidos {n_municipios_removidos} municípios ({n_linhas_removidas} linhas) "
              f"sem correspondência na tabela de população.")

    todos_municipios = pd.concat([
        srag["municipio"], populacao["municipio"], leitos["municipio"]
    ]).unique()
    semanas = pd.period_range(srag["semana"].min(), srag["semana"].max(), freq="W")

    grade = pd.MultiIndex.from_product(
        [todos_municipios, semanas], names=["municipio", "semana"]
    ).to_frame(index=False)

    dataset = grade.merge(srag, on=["municipio", "semana"], how="left")
    dataset = dataset.merge(populacao, on="municipio", how="left")
    dataset = dataset.merge(leitos, on="municipio", how="left")
    dataset = dataset.merge(temperatura, on=["municipio", "semana"], how="left")

    colunas_contagem = [
        "casos_srag", "casos_influenza", "casos_covid", "obitos",
        "casos_uti", "casos_com_comorbidade", "casos_vacinados", "casos_idosos",
        "taxa_obito", "taxa_uti", "taxa_comorbidade", "taxa_vacinados", "taxa_idosos",
        "casos_surto", "casos_saturacao_baixa", "casos_dispneia", "casos_desc_resp",
        "casos_vent_invasiva", "casos_pcr_positivo", "casos_antigenico_positivo",
        "casos_sars2", "casos_vsr", "casos_testados", "casos_fator_risco",
        "casos_gestantes", "casos_tabagistas", "casos_zona_rural",
        "casos_vacinados_covid", "casos_febre", "casos_tosse", "casos_referenciados",
        "taxa_cadeia_surto", "taxa_saturacao_baixa", "taxa_dispneia",
        "taxa_desc_respiratorio", "taxa_ventilacao_invasiva",
        "taxa_positividade_pcr", "taxa_positividade_antigenico", "taxa_sars2",
        "taxa_vsr", "taxa_testagem", "taxa_fator_risco", "taxa_gestantes",
        "taxa_tabagismo", "taxa_zona_rural", "taxa_vacinacao_covid",
        "taxa_febre", "taxa_tosse", "indice_fluxo_referencia_hospitalar",
    ]
    for coluna in colunas_contagem:
        if coluna in dataset.columns:
            dataset[coluna] = dataset[coluna].fillna(0)
    # NOTA: idade_media e CO_REGIONA ficam FORA dessa lista de propósito —
    # mesma lógica de regional_saude: em semanas sem nenhum caso, não faz
    # sentido "zerar" a idade média ou o código da regional.

    return dataset, todos_municipios

"""## Geração do dataset final de 2024"""

# ========================================================================
# GERAÇÃO DO DATASET FINAL 2024
# ========================================================================

_COD_PARA_NOME_MUNICIPIO = None  # preenchido dentro de carregar_populacao_2024()


def gerar_dataset_final_2024():
    print("Carregando e tratando cada fonte (recorte: São Paulo, 2024)...")
    populacao = carregar_populacao_2024()          # preenche _COD_PARA_NOME_MUNICIPIO
    leitos = carregar_leitos_2024()
    temperatura = carregar_temperatura_sp_2024()
    srag = carregar_srag_2024()

    print("Completando a grade de município x semana (semanas sem SRAG viram 0)...")
    dataset, todos_municipios = completar_grade_e_unir(srag, populacao, leitos, temperatura)

    print(f"Geocodificando {len(todos_municipios)} municípios (usado para região + temperatura)...")
    municipios_coords = geocodificar_municipios(todos_municipios)

    print("Classificando região de cada município...")
    mapa_regiao = classificar_regiao(municipios_coords)
    dataset["regiao"] = dataset["municipio"].map(mapa_regiao).fillna("Não informado")

    print("Geocodificando estações de temperatura...")
    estacoes = temperatura["municipio"].unique().tolist()
    estacoes_coords = geocodificar_municipios(estacoes)

    print("Preenchendo temperaturas ausentes por proximidade geográfica...")
    dataset = preencher_temperatura_por_proximidade(dataset, temperatura, estacoes_coords, municipios_coords)

    print("Calculando colunas derivadas (sazonalidade, capacidade, tendência)...")
    dataset = dataset.sort_values(["municipio", "semana"]).reset_index(drop=True)

    dataset["casos_por_10k"] = dataset["casos_srag"] / dataset["populacao"] * 10_000
    dataset["leitos_por_1000_hab"] = dataset["LEITOS_SUS"] / dataset["populacao"] * 1000

    dataset["data_inicio_semana"] = dataset["semana"].dt.start_time
    dataset["ano"] = dataset["data_inicio_semana"].dt.year
    dataset["semana_numero"] = dataset["data_inicio_semana"].dt.isocalendar().week
    dataset["data_formatada"] = dataset["data_inicio_semana"].apply(formatar_data_br)

    dataset["casos_srag_semana_anterior"] = dataset.groupby("municipio")["casos_srag"].shift(1)
    dataset["media_movel_3_semanas_casos"] = dataset.groupby("municipio")["casos_srag"].transform(
        lambda serie: serie.shift(1).rolling(window=3, min_periods=1).mean()
    )
    dataset["variacao_temp"] = dataset.groupby("municipio")["temp_media"].diff()
    dataset["variacao_casos_pct"] = (
        dataset.groupby("municipio")["casos_srag"].pct_change()
        .replace([float("inf"), float("-inf")], None)
    )

    dataset = dataset.drop(columns=["semana", "data_inicio_semana"])

    colunas_finais = [
        "municipio", "regiao", "regional_saude", "ano", "semana_numero", "data_formatada",
        "casos_srag", "casos_influenza", "casos_covid", "obitos", "casos_uti",
        "casos_com_comorbidade", "casos_vacinados", "casos_idosos",
        "taxa_obito", "taxa_uti", "taxa_comorbidade", "taxa_vacinados", "taxa_idosos",
        "populacao", "LEITOS_SUS", "leitos_uti_sus", "leitos_uti_adulto_sus",
        "leitos_uti_pediatrico_sus", "leitos_uti_neonatal_sus", "LEITOS_EXISTENTES",
        "proporcao_leitos_sus", "n_hospitais_sus", "leitos_por_1000_hab",
        "temp_media", "temp_imputada", "casos_por_10k",
        "casos_srag_semana_anterior", "media_movel_3_semanas_casos",
        "variacao_temp", "variacao_casos_pct",
        "taxa_cadeia_surto", "taxa_saturacao_baixa", "taxa_dispneia",
        "taxa_desc_respiratorio", "taxa_ventilacao_invasiva", "tempo_medio_uti_dias",
        "taxa_positividade_pcr", "taxa_positividade_antigenico", "taxa_sars2", "taxa_vsr",
        "taxa_testagem", "atraso_notificacao_dias", "atraso_coleta_dias",
        "indice_fluxo_referencia_hospitalar", "atraso_internacao_dias",
        "taxa_fator_risco", "taxa_gestantes", "taxa_tabagismo", "taxa_zona_rural",
        "taxa_vacinacao_covid", "taxa_febre", "taxa_tosse",
        "atraso_digitacao_dias", "tempo_ate_desfecho_dias",
        # 2 colunas novas, pedidas para esta rodada:
        "idade_media", "CO_REGIONA",
    ]
    colunas_finais = [c for c in colunas_finais if c in dataset.columns]
    faltando = [c for c in colunas_finais if c not in dataset.columns]
    dataset = dataset[colunas_finais]

    dataset.to_csv(SAIDA, index=False)
    print(f"\nDataset final salvo em: {SAIDA}")
    print(f"Municípios únicos: {dataset['municipio'].nunique()}")
    print(f"Total de linhas: {len(dataset)}")
    return dataset

dataset_2024 = gerar_dataset_final_2024()
dataset_2024.head()

"""## Validação — a base de 2024 tem a mesma estrutura da base de 2025?

Compara colunas (nomes, ordem e tipo) da base de 2024 recém-gerada com as linhas `ano == 2025`
já existentes em `vigiar_sp_formatado.xlsx`. As 2 colunas novas (`idade_media`, `CO_REGIONA`) são
esperadas como diferença — elas ainda não existem na base de 2025. Se você quiser consolidar as
duas bases de fato, essas 2 colunas vão precisar ser preenchidas também para 2025 (rodando essa
mesma lógica sobre `srag_2025_completo.csv`), senão ficam nulas nas linhas de 2025.
"""

import openpyxl
import pandas as pd

wb = openpyxl.load_workbook(VIGIAR_REF_PATH, read_only=True, data_only=True)
ws = wb["Dados"]
it = ws.iter_rows(values_only=True)
header_2025 = list(next(it))

colunas_2024 = list(dataset_2024.columns)
colunas_novas = ["idade_media", "CO_REGIONA"]
colunas_2024_sem_novas = [c for c in colunas_2024 if c not in colunas_novas]

print("Colunas de 2025:", len(header_2025))
print("Colunas de 2024 (sem as 2 novas):", len(colunas_2024_sem_novas))

if header_2025 == colunas_2024_sem_novas:
    print("\nOK — mesmos nomes de coluna, na mesma ordem.")
else:
    print("\nATENÇÃO — diferença encontrada:")
    for i, (a, b) in enumerate(zip(header_2025, colunas_2024_sem_novas)):
        if a != b:
            print(f"  posição {i}: 2025='{a}'  |  2024='{b}'")
    if len(header_2025) != len(colunas_2024_sem_novas):
        print(f"  quantidade de colunas diferente: 2025={len(header_2025)}, 2024={len(colunas_2024_sem_novas)}")

print("\nColunas novas em 2024 (esperado, ainda não existem em 2025):", colunas_novas)

"""## Comentários de coluna para o Oracle Select AI (`COMMENT ON TABLE` / `COMMENT ON COLUMN`)

Gera o script SQL a partir da mesma aba **Dicionário de Dados** do `vigiar_sp_formatado.xlsx`, adicionando as 2 colunas novas. Ajuste `NOME_DA_TABELA` para o nome real da tabela na sua Autonomous Database antes de rodar o script no ADB.
"""

NOME_DA_TABELA = "NOME_DA_TABELA"  # <-- AJUSTE AQUI

wb = openpyxl.load_workbook(VIGIAR_REF_PATH, read_only=True, data_only=True)
ws = wb["Dicionário de Dados"]
linhas_dicionario = list(ws.iter_rows(values_only=True))[1:]  # pula cabeçalho

descricoes_novas = {
    "idade_media": (
        "Idade média (em anos) dos casos de SRAG notificados no município na semana, "
        "calculada apenas sobre os registros em que a idade foi informada em anos no "
        "SIVEP-Gripe (campo NU_IDADE_N, quando TP_IDADE = Ano)."
    ),
    "CO_REGIONA": (
        "Código numérico oficial da Regional de Saúde (GVE) no SIVEP-Gripe, complementar "
        "ao nome já disponível em regional_saude — permite cruzamento direto com outras "
        "bases do SUS que usem esse mesmo código."
    ),
}

linhas_sql = [
    "-- Gerado automaticamente a partir do dicionario de dados do VigiAr SP",
    f"COMMENT ON TABLE {NOME_DA_TABELA} IS 'Base agregada de SRAG (SIVEP-Gripe) por "
    "municipio e semana epidemiologica, Estado de Sao Paulo. Alimenta o modelo preditivo "
    "de surto (Random Forest) e consultas em linguagem natural via Oracle Select AI.';",
    "",
]
for _, coluna, _, _, descricao in linhas_dicionario:
    descricao_sql = str(descricao).replace("'", "''")
    linhas_sql.append(f"COMMENT ON COLUMN {NOME_DA_TABELA}.{coluna} IS '{descricao_sql}';")

linhas_sql.append("")
linhas_sql.append("-- Colunas novas desta rodada (nao existiam na base de 2025):")
for coluna, descricao in descricoes_novas.items():
    descricao_sql = descricao.replace("'", "''")
    linhas_sql.append(f"COMMENT ON COLUMN {NOME_DA_TABELA}.{coluna} IS '{descricao_sql}';")

script_sql = "\n".join(linhas_sql)
with open(SAIDA_SQL, "w", encoding="utf-8") as f:
    f.write(script_sql)

print(script_sql[:800])
print("...")
print(f"\nScript salvo em: {SAIDA_SQL}")

"""## Download dos resultados"""

from google.colab import files
files.download(SAIDA)
files.download(SAIDA_SQL)